server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cybersec_db
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=REPLACE_WITH_A_STRONG_SECRET_KEY_AT_LEAST_32_CHARS
jwt.expiration-ms=86400000


spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null